### ISSUE TITLE
Protocol Buffer files not provided

### ISSUE THREAD

**Issue by innomon** [digital-asset/canton#4]
Where can I find the,  `.proto` files corresponding to  the protocol buffer API defined in the [canton doc  web site](https://www.canton.io/docs/stable/user-manual/usermanual/administration.html) ?

**Comment by daravep** [comment]
Canton based system expose two APIs: The "daml generic" ledger API, which is the same for any DAML integration and Canton specific APIs (admin API and sequencer API). 

We haven't packaged the admin API definitions yet as we still consider them to be an internal API that is subject to frequent change. Are you looking for them out of curiosity or are you trying to build an application against the admin API? 

If you are looking for the ledger API definitions, they are here: https://github.com/digital-asset/daml/tree/main/ledger-api/grpc-definitions

**Comment by innomon** [comment]
Thanks for the clarification.
 I was looking into Canton, to develop a deeper understanding of the DLT aspect. I am also building a DAML app.
