### ISSUE TITLE
GRPC Runtime Exception on AWS EKS.

### ISSUE THREAD

**Issue by raphson93** [digital-asset/canton#81]
SDK version?

- 2.5.0

Where the app deploy?

- AWS K8s

What happen?

- connection closed occasionally when the app connected to the participant node.
![image](https://user-images.githubusercontent.com/19220265/222611780-3b02e65a-2e94-4540-8ace-cdcc8d8a29df.png)
![image](https://user-images.githubusercontent.com/19220265/222611932-011ea142-8b82-474c-80b9-8fbc25e60caf.png)

**Comment by mziolekda** [comment]
I would have a few questions

- Did you manage to get any data across?
- Are you set-up to use TLS? How did you setup canton and the client in that regard?
- What technology stack are you using on the client side?

**Comment by raphson93** [comment]
@mziolekda 

Did you manage to get any data across?
**_Once the connection drop after idle for some time, our app unable to reconnect back to the session._**

Are you set-up to use TLS? How did you setup canton and the client in that regard?
_**No. Could you provide a sample regarding the TLS setup? I can share our domain and participant cfg with you:**_
![image](https://user-images.githubusercontent.com/19220265/222664973-00f09d13-74cf-4800-8dcc-2056279c062f.png)

![image](https://user-images.githubusercontent.com/19220265/222665637-88523b77-35eb-439d-9365-73ddcee84ae9.png)

What technology stack are you using on the client side?
_**We hosted our app on EKS and connected through AWS classic load balancer.**_

**Comment by mziolekda** [comment]
1. The call that is failing is one that uses server-side streaming. Hence my question regarding if you were ever able to successfully get any data across such call? If it works initially but stops would point to a very different culprit than if it never worked.

2. Further, I am still struggling to picture what happened in what order:

> Once the connection drop after idle for some time, our app unable to reconnect back to the session.
It is not clear to me if the idle comes first or the connection drop comes first.

Could you describe what happens when e.g.
- server start at ...
- app start at ...
- app makes requests X,Y,Z successfully at ...
- app makes request unsuccessfully at ...
- app idle from to ...
- app restart perhaps?

3. Are you using java bindings to connect to canton?

**Comment by raphson93** [comment]
1. There's a setting for classic load balancer call "Idle Timeout". So I assume the behavior is kill the connection after the services idle for n amount of time.

2. I think the idle come first, hence the connection closed after it hits the "Idle Timeout" we configured earlier on. The connection is normal after we restarted our kubernetes pods.

3. No.

**Comment by tudor-da** [comment]
Hi @raphson93 ,

Looking at the stack traces provided in the screenshots, it seems that you are using some part at least of the Java bindings client libraries for connecting to Canton (I see `com.daml.grpc.adapter.client.rs.BufferingResponserObserver` in there). Can you detail what part of the client libraries you are using.

In the server-side stack-trace, it looks like the client is trying to connect to the server using a TLS handshake (the header preface received bytes start with x16 which looks like the TLS record protocol header). Can it be that your client is configured to use TLS, then?

> No. Could you provide a sample regarding the TLS setup? I can share our domain and participant cfg with you:

You can check the docs for TLS configuration for the API [here](https://docs.daml.com/canton/usermanual/apis.html#tls-configuration)

**Comment by raphson93** [comment]
Hi @tudor-da 
> Looking at the stack traces provided in the screenshots, it seems that you are using some part at least of the Java bindings client libraries for connecting to Canton (I see `com.daml.grpc.adapter.client.rs.BufferingResponserObserver` in there). Can you detail what part of the client libraries you are using and how?

After going through the whole the code library, I think we have a long running process to listen on the ledger port:
```
public class TraceUtil {

    public static DamlLedgerClient client(String host, int port, TextMapPropagator propagator) {
        NettyChannelBuilder nettyChannel = NettyChannelBuilder.forAddress(host, port)
                .intercept(new TraceInterceptor())
                .intercept(new OtClientInterceptor(propagator));
        return DamlLedgerClient.newBuilder(nettyChannel).build();
}

public void run(String... args) throws Exception {
        DamlLedgerClient client = TraceUtil.client2(ip, port, PROPAGATOR);
        client.connect();
```



> Can it be that your client is configured to use TLS, then?

Is there any way to verify it ?

**Comment by tudor-da** [comment]
> Hi @tudor-da
> 
> > Looking at the stack traces provided in the screenshots, it seems that you are using some part at least of the Java bindings client libraries for connecting to Canton (I see `com.daml.grpc.adapter.client.rs.BufferingResponserObserver` in there). Can you detail what part of the client libraries you are using and how?
> 
> After going through the whole code repository, I think we have a long running process to listen on the ledger port:
> 
> ```
> public class TraceUtil {
> 
>     public static DamlLedgerClient client(String host, int port, TextMapPropagator propagator) {
>         NettyChannelBuilder nettyChannel = NettyChannelBuilder.forAddress(host, port)
>                 .intercept(new TraceInterceptor())
>                 .intercept(new OtClientInterceptor(propagator));
>         return DamlLedgerClient.newBuilder(nettyChannel).build();
> }
> 
> public void run(String... args) throws Exception {
>         DamlLedgerClient client = TraceUtil.client2(ip, port, PROPAGATOR);
>         client.connect();
> ```
> 
> > Can it be that your client is configured to use TLS, then?
> 
> Is there any way to verify it ?

Hard to advise without in-depth knowledge of your system's setup, but please check your setup and make sure that you are using either plaintext on both ends (client and server) or TLS on both.

**Comment by raphson93** [comment]
> Hard to advise without in-depth knowledge of your system's setup, but please check your setup and make sure that you are using either plaintext on both ends (client and server) or TLS on both.

hi @tudor-da , @mziolekda 
I checked both domain config and the code itself, the protocol we used should be PLAINTEXT.

**Comment by mziolekda** [comment]
@raphson93 from what we have been able to gather so far, the problem is not related to the canton ledger server that implements the ApiActiveContractService. The error is reported by netty server while it processes the low level HTTP2 traffic. All the indicators point to the client app that is trying to send TLS data through a link that is expecting a plain-text conversation. The issue most likely originates in the misconfiguration of the client app, the proxies or the load balancer.

I would start debugging this problem by moving the server and the client closer together (e.g. to same VM) and peeling off layers of indirection (the proxies, load balancers etc.) and then adding them again until the problem resurfaces.

If that doesn't help and you need further assistance, I would ask you to contact the support who can help you with configuration of the client application.

**Comment by raphson93** [comment]
hi @mziolekda , let me update what my team has been done so far:
- We modified our code to retry the transaction once the connection closed.

Before:
```
transactions.onErrorResumeNext(throwable -> {log.info("GRPC Error"); System.out.println("GRPC Error do nothing");})
              .subscribe(t -> {
```

After:
```
transactions.retry()
                .subscribe(t -> {
```

But now there is another issue we facing now, the java process will be suspended/freeze and will not respond to the request if there is an update in our contract.

**Comment by daravep** [comment]
Hi @raphson93 The Github repo is meant to be used for issues within canton. Please use the normal support channels / your CX contact to help with application development. Thanks!
