### ISSUE TITLE
Dars is not available in the list after uploading.

### ISSUE THREAD

**Issue by raphson93** [digital-asset/canton#82]
SDK Version: 2.5.0

What happened:
Dar file is not visible with `"participan1.dars.list()"` after using `upload-dar` command.
![image](https://user-images.githubusercontent.com/19220265/223317293-6413d238-7d63-4364-b6f1-b05c69b43c1a.png)

Sample Dar Name: abc.dar with hash `"ABC"`

However the packages is available if we use `"packages.list_contents("hash")"` command
![image](https://user-images.githubusercontent.com/19220265/223317688-8d6257ef-6d77-47e9-98da-a78cf1cf45ec.png)

**Comment by daravep** [comment]
Hi @raphson93 
Please have a look at the fourth item in the current limitations section: https://docs.daml.com/2.7.0/canton/architecture/requirements/requirements.html#id26
I hope this resolves your question. This will likely be fixed in 3.0.

**Comment by raphson93** [comment]
hi @daravep , thanks for the reply.
Do you know when will canton v3.0 available ?

**Comment by daravep** [comment]
GA ready, roughly in 12 months. But don't hold me to that. Preview might be earlier. But for your issue, I just recommend to upload via the canton console and you are good.
